apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    name: memcached
spec:
  type: LoadBalancer
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
  selector:
    app: memcached

---


apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    app: memcached
  name: memcached
  namespace: default

spec:
  replicas: 1
  selector:
    app: memcached
  template:
    metadata:
      labels:
        app: memcached

    spec:
      containers:
      - name: memcached
        image: sameersbn/memcached
        ports:
        - name: memcached
          containerPort: 11211
          protocol: TCP

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

status:
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1
