apiVersion: v1
kind: Service
metadata:
  labels:
    name: fpm
  name: fpm
spec:
  ports:
    - name: fpm
      port: 9000
  selector:
    app: cb7fpm
  type: LoadBalancer

---

apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    app: cb7fpm
  name: cb7fpm
  namespace: default

spec:
  replicas: 1
  selector:
    app: cb7fpm
  template:
    metadata:
      labels:
        app: cb7fpm

    spec:
      containers:
      - name: cb7fpm
        image: DOCKER_REGISTRY:5000/cb7fpm
        ports:
        - name: fpm
          containerPort: 9000
          protocol: TCP

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

status:
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1
                                
