apiVersion: v1
kind: Service
metadata:
  name: my-wordpress
  labels:
    name: my-wordpress

spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: mysql
    port: 3306
    protocol: TCP

  type: LoadBalancer

  selector:
    app: my-wordpress
