apiVersion: v1
kind: ReplicationController

metadata:
  name: ready-to-deploy-wordpress
  namespace: default
  

  labels:
    app: my-wordpress



spec:
  replicas: 1
  selector:
    app: my-wordpress
  template:
    metadata:
      name: my-wordpress
      creationTimestamp: null
      labels:
        app: my-wordpress


    
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - name: wordpress
          containerPort: 9191
          protocol: TCP


        env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:3306
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: abc123
        - name: WORDPRESS_DB_NAME
          value: Wordpress



      - name: mysql
        image: mariadb
        ports:
        - name: mariadb
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: abc123

    status:
      replicas: 1
      fullyLabeledReplicas: 1
      observedGeneration: 6

