apiVersion: v1
kind: Service
metadata:
  name: my-wordpress
  labels:
    name: my-wordpress

spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8888

  selector:
    app: my-wordpress

---
apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    app: my-wordpress
  name: ready-to-deploy-wordpress
  namespace: default

spec:
  replicas: 1
  selector:
    app: my-wordpress
  template:
    metadata:
      labels:
        app: my-wordpress

    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - name: http
          containerPort: 80
          protocol: TCP

        env:
        - name: WORDPRESS_DB_HOST
          value: my-wordpress:3306
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: abc123
        - name: WORDPRESS_DB_NAME
          value: Wordpress

      - name: mysql
        image: mariadb
        ports:
        - name: mariadb
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: abc123

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

status:
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1

