apiVersion: v1
kind: Service
metadata:
  name: varnish-service-a
  labels:
    name: varnish-service-a
spec:
  ports:
    - port: 80
      name: varnish
  selector:
    unit: varnish-service-a
  type: LoadBalancer
