apiVersion: v1
kind: Service
metadata:
  namespace: magento2
  labels:
    name: fpm
  name: fpm
spec:
  ports:
    - port: 9000
  selector:
    app: fpm
  #type: LoadBalancer
  clusterIP: None
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: fpm
  name: fpm
  namespace: magento2

spec:
  selector:
    matchLabels:
      app: fpm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fpm

    spec:
      containers:
      - image: registry.example.local:5000/php-fpm
        imagePullPolicy: Always
        name: fpm
        ports:
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
            - mountPath: /var/www/html:rw
              name: magento
      volumes:
      - name: magento
        nfs:
          server: 192.168.50.85
          path: "/srv/nfsshare/k8s-stage/magento"

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 5

