apiVersion: v1
kind: Service
metadata:
  labels:
    name: fpm
  name: fpm
spec:
  ports:
    - name: fpm
      port: 9000
      protocol: TCP
      #nodePort: 30000
      #targetPort: 9000
  selector:
    app: fpm
  type: LoadBalancer

---

apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    app: fpm
  name: fpm
  namespace: default

spec:
  replicas: 1
  selector:
    app: fpm
  template:
    metadata:
      labels:
        app: fpm

    spec:
      containers:
      - name: fpm
        image: localhost:5000/php
        ports:
        - name: fpm
          containerPort: 9000
          protocol: TCP

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

status:
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1
