apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql

spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
  selector:
    app: mysql
  type: ClusterIP

---
apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    app: mysql
  name: mysql
  namespace: default

spec:
  replicas: 1
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
      - name: mysql
        image: bitnami/mariadb:latest
        ports:
        - name: mariadb
          containerPort: 3306
          protocol: TCP
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: abc1234
        - name: MARIADB_USER
          value: magento
        - name: MARIADB_PASSWORD
          value: abc1234
        - name: MARIADB_DATABASE
          value: magento
        volumeMounts:
            - mountPath: /var/lib/mysql:rw
              name: host-mysql
            - mountPath: /var/log/mysql:rw
              name: host-logs

      volumes:
      - name: host-mysql
        hostPath:
          path: /datas/mysql
      - name: host-logs
        hostPath:
          path: /datas/logs

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

status:
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1
