apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql

spec:
  ports:
    - name: mysql
      port: 3306
  selector:
    app: mysql
  type: ClusterIP

---

apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    app: mysql
  name: mysql
  namespace: default

spec:
  replicas: 1
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql

    spec:
      nodeSelector:
        name: master
      containers:
      - name: mysql
        image: mysql/mysql-server:5.7
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_USER
          value: magento
        - name: MYSQL_PASSWORD
          value: abc1234
        - name: MYSQL_ROOT_PASSWORD
          value: abc1234
        - name: MYSQL_DATABASE
          value: magento
        volumeMounts:
            - mountPath: /var/lib/mysql
              name: host-mysql
            - mountPath: /var/log/mysql
              name: host-logs

      volumes:
      - name: host-mysql
        hostPath:
          path: /datas/mysql
      - name: host-logs
        hostPath:
          path: /datas/logs
