apiVersion: v1
kind: Service
metadata:
  namespace: magento2
  name: mysql
  labels:
    name: mysql

spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
  selector:
    app: mysql
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: magento2
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mariadb:10.2.7
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: abc1234
        - name: MYSQL_USER
          value: magento
        - name: MYSQL_PASSWORD
          value: abc1234
        - name: MYSQL_DATABASE
          value: magento
        - name: wait_timeout
          value: "180"
        volumeMounts:
            - mountPath: /var/lib/mysql:rw
              name: host-mysql

      volumes:
      - name: host-mysql
        nfs:
          server: 192.168.50.85
          path: "/srv/nfsshare/k8s-stage/magento_mysql"

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
