apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  ports:
    - port: 80
  selector:
    app: nginx
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginxip
  name: nginxip
spec:
  ports:
    - port: 80
  selector:
    app: nginx
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: localhost:5000/nginx
        name: nginx
        env:
         - name: VARHOST
           value: fpm
         - name: MAGENTO_VERSION
#        command: ["/bin/sh","-c"]
#        args: ["/usr/local/bin/magento-install.sh"]
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
            - mountPath: /var/www/html
              name: magento
      volumes:
      - name: magento
        hostPath:
          path: /datas/magento
