apiVersion: v1
kind: Service
metadata:
  namespace: magento2
  name: nginx
  labels:
    name: nginx
spec:
  ports:
    - port: 80
  selector:
    app: nginx
  type: NodePort 

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: magento2
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: infra.afdata.local:5000/nginx
        name: nginx
        env:
         - name: VARHOST
           value: fpm
         - name: MAGENTO_VERSION
           value: 2.1.1
        #command: ["/bin/sh","-c"]
        #args: ["/tmp/magento-install.sh"]
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
            - mountPath: /var/www/html:rw
              name: magento
            - mountPath: /etc/nginx:rw
              name: nginx-config
      volumes:
      - name: magento
        nfs:
          server: 192.168.50.85
          path: "/srv/nfsshare/k8s-stage/magento2"
      - name: nginx-config
        nfs:
          server: 192.168.50.85
          path: "/srv/nfsshare/k8s-stage/magento_nginx"

