apiVersion: v1
kind: Service
metadata:
  namespace: magento2
  name: nginx
  labels:
    name: nginx
spec:
  ports:
    - port: 80
  selector:
    app: nginx
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: magento2
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: infra.afdata.local:5000/nginx
        name: nginx
        env:
         - name: VARHOST
           value: fpm
         - name: MAGENTO_VERSION
           value: "2.3"
         - name: MAGENTO_BASE_URL
           value: "http://magento.example.local/"
         - name: ADMIN_PASSWORD
           value: "GkxK8P52M7b32Rz"
         - name: ADMIN_EMAIL
           value: "user@example.com"
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
            - mountPath: /var/www/html:rw
              name: magento
      volumes:
      - name: magento
        nfs:
          server: 192.168.50.85
          path: "/srv/nfsshare/k8s-stage/magento"
