apiVersion: v1
kind: Service
metadata:
  name: pxc-node3
  labels:
    name: pxc-node3

spec:
  ports:
    - name: mysql
      port: 3306
    - name: state-snapshot-transfer
      port: 4444
    - name: replication-traffic
      port: 4567
    - name: incremental-state-transfer
      port: 4568
  selector:
    node: pxc-node3


---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pxc-node3 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        node: pxc-node3 
        unit: pxc-cluster
    spec:
      nodeSelector:
          kubernetes.io/hostname: HOSTNAME_OF_MINION_3

      containers:
        - image: DOCKER_REGISTRY:5000/galera
          name: pxc-node3
          ports:
            - containerPort: 3306
            - containerPort: 4444
            - containerPort: 4567
            - containerPort: 4568
          env:
            - name: GALERA_CLUSTER
              value: "true"
            - name: WSREP_CLUSTER_ADDRESS
              value: gcomm://
            - name: WSREP_SST_USER
              value: sst
            - name: WSREP_SST_PASSWORD
              value: sst
            - name: MYSQL_USER
              value: superuser
            - name: MYSQL_PASSWORD
              value: abc123
            - name: MYSQL_ROOT_PASSWORD
              value: abc123
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: host-mysql
            - mountPath: /var/log/mysql
              name: host-logs

      volumes:
        - name: host-mysql
          hostPath:
            path: /datas/mysql
        - name: host-logs
          hostPath:
            path: /datas/logs

