apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: magento.afdata.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
